/*
 * libslp-tapi
 *
 * Copyright (c) 2011 Samsung Electronics Co., Ltd. All rights reserved.
 *
 * Contact: Ja-young Gu <jygu@samsung.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef _TEL_CS_CONN_H_
#define _TEL_CS_CONN_H_

#include <TapiCommon.h>

#ifdef __cplusplus
extern "C" {
#endif

#define TAPI_CS_TYPE_ASYNC					(0 << 24)
#define TAPI_CS_TYPE_SYNC					(1 << 24)

#define	TAPI_CS_SERVICE_CALL				TAPI_EVENT_CLASS_CALL_VOICE	// TAPI_EVENT_CLASS_CALL_DATA
#define	TAPI_CS_SERVICE_SIM					TAPI_EVENT_CLASS_SIM
#define	TAPI_CS_SERVICE_NETTEXT				TAPI_EVENT_CLASS_NETTEXT
#define	TAPI_CS_SERVICE_NETWORK				TAPI_EVENT_CLASS_NETWORK
#define	TAPI_CS_SERVICE_SS					TAPI_EVENT_CLASS_SS
#define	TAPI_CS_SERVICE_SIMATK				TAPI_EVENT_CLASS_SAT
#define	TAPI_CS_SERVICE_GPRS				TAPI_EVENT_CLASS_DATA
#define	TAPI_CS_SERVICE_SOUND				TAPI_EVENT_CLASS_SOUND
#define	TAPI_CS_SERVICE_UTIL				TAPI_EVENT_CLASS_UTIL

// Voice Call/Data Call Service
#define	TAPI_CS_CALL_SETUP					TAPI_EVENT_CALL_SETUP_CNF
#define	TAPI_CS_CALL_ANSWER					TAPI_EVENT_CALL_ANSWER_CNF
#define	TAPI_CS_CALL_RELEASE				TAPI_EVENT_CALL_RELEASE_CNF
#define	TAPI_CS_CALL_RELEASEALL				TAPI_EVENT_CALL_RELEASE_ALL_CNF
#define	TAPI_CS_CALL_RELEASEALL_ACTIVE		TAPI_EVENT_CALL_RELEASE_ALL_ACTIVE_CNF
#define	TAPI_CS_CALL_RELEASEALL_HELD		TAPI_EVENT_CALL_RELEASE_ALL_HELD_CNF
#define	TAPI_CS_CALL_DTMF					TAPI_EVENT_CALL_SEND_DTMF_CNF
#define	TAPI_CS_CALL_ACTIVATE				TAPI_EVENT_CALL_RETRIEVE_CNF
#define	TAPI_CS_CALL_HOLD					TAPI_EVENT_CALL_HOLD_CNF
#define	TAPI_CS_CALL_SWAP					TAPI_EVENT_CALL_SWAP_CNF
#define	TAPI_CS_CALL_SETUPCONFCALL			TAPI_EVENT_CALL_SETUPCONFERENCE_CNF
#define	TAPI_CS_CALL_SPLITCONFCALL			TAPI_EVENT_CALL_SPLITCONFERENCE_CNF
#define	TAPI_CS_CALL_TRANSFERCALL			TAPI_EVENT_CALL_TRANSFER_CNF
#define	TAPI_CS_CALL_GETACTIVELINE			TAPI_EVENT_CALL_GET_LINEID_CNF
#define	TAPI_CS_CALL_SETACTIVELINE			TAPI_EVENT_CALL_SET_LINEID_CNF
#define	TAPI_CS_CALL_GETPRIVACYMODE			TAPI_EVENT_CALL_GET_PRIVACYMODE_CNF
#define	TAPI_CS_CALL_SETPRIVACYMODE			TAPI_EVENT_CALL_SET_PRIVACYMODE_CNF
#define	TAPI_CS_CALL_FLASHINFO				TAPI_EVENT_CALL_FLASHINFO_CNF
#define	TAPI_CS_CALL_EXITEMERGENCYMODE		TAPI_EVENT_CALL_EXIT_EMERGENCYMODE_CNF
#define	TAPI_CS_CALL_GETCALLTIME			TAPI_EVENT_CALL_TIME_CNF

// should be confirm event
#define	TAPI_CS_CALL_DEFLECT				(TAPI_EVENT_CALL_CNF_MAX + 1) // ? undefined confirm
#define	TAPI_CS_CALL_ACTIVATECCBS			(TAPI_EVENT_CALL_CNF_MAX + 2) // undefiend confirm - ipc_rx_gencmd.c Not supported.
// sync API
#define	TAPI_CS_CALL_GETSTATUS				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_CALL_CNF_MAX + 3)
#define	TAPI_CS_CALL_GETDURATION			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_CALL_CNF_MAX + 4)
#define	TAPI_CS_CALL_GETCONFERENCELIST		(TAPI_CS_TYPE_SYNC+TAPI_EVENT_CALL_CNF_MAX + 5)

// SIM Service
#define	TAPI_CS_SIM_EVENT_MAX				TAPI_EVENT_SIM_AUTHENTICATION_CNF
#define	TAPI_CS_SIM_GETINDICATIONINFO		TAPI_EVENT_SIM_GET_INDICATION_CNF
#define	TAPI_CS_SIM_SETINDICATIONINFO		TAPI_EVENT_SIM_SET_INDICATION_CNF
#define	TAPI_CS_SIM_GETMAILBOXINFO			TAPI_EVENT_SIM_GET_MAILBOX_CNF
#define	TAPI_CS_SIM_SETMAILBOXINFO			TAPI_EVENT_SIM_SET_MAILBOX_CNF
#define	TAPI_CS_SIM_SETLANGUAGE				TAPI_EVENT_SIM_SET_LANGUAGE_CNF
#define	TAPI_CS_SIM_RSIMACCESS				TAPI_EVENT_SIM_RSIM_ACCESS_CNF
#define	TAPI_CS_SIM_VERIFYSEC				TAPI_EVENT_SIM_VERIFY_SEC_CNF
#define	TAPI_CS_SIM_VERIFYPUK				TAPI_EVENT_SIM_VERIFY_PUK_CNF
#define	TAPI_CS_SIM_CHANGEPIN				TAPI_EVENT_SIM_CHANGE_PINS_CNF
#define	TAPI_CS_SIM_DISABLESEC				TAPI_EVENT_SIM_DISABLE_SEC_CNF
#define	TAPI_CS_SIM_ENABLESEC				TAPI_EVENT_SIM_ENABLE_SEC_CNF
#define	TAPI_CS_SIM_GETPERSSTATUS			TAPI_EVENT_SIM_PERS_STATUS_CNF
#define	TAPI_CS_SIM_DISABLEPERS				TAPI_EVENT_SIM_DISABLE_PERS_CNF
#define	TAPI_CS_SIM_ENABLEPERS				TAPI_EVENT_SIM_ENABLE_PERS_CNF
#define	TAPI_CS_SIM_DISABLEFDN				TAPI_EVENT_SIM_DISABLE_FDNMODE_CNF
#define	TAPI_CS_SIM_ENABLEFDN				TAPI_EVENT_SIM_ENABLE_FDNMODE_CNF
#define	TAPI_CS_SIM_PB_GETCOUNT				TAPI_EVENT_SIM_PB_STORAGE_COUNT_CNF
#define	TAPI_CS_SIM_PB_GETMETAINFO			TAPI_EVENT_SIM_PB_ENTRY_INFO_CNF
#define	TAPI_CS_SIM_PB_READRECORD			TAPI_EVENT_SIM_PB_ACCESS_READ_CNF
#define	TAPI_CS_SIM_PB_UPDATERECORD			TAPI_EVENT_SIM_PB_UPDATE_CNF
#define	TAPI_CS_SIM_PB_DELETERECORD			TAPI_EVENT_SIM_PB_DELETE_CNF
#define	TAPI_CS_SIM_GETPBCAPABILITYINFO		TAPI_EVENT_SIM_PB_CAPABILITY_INFO_CNF
#define	TAPI_CS_SIM_SAPCONNECTREQUEST		TAPI_EVENT_SIM_SAP_CONNECT_CNF
#define	TAPI_CS_SIM_SAPCONNECTSTATUS		TAPI_EVENT_SIM_SAP_CONNECT_STATUS_CNF
#define	TAPI_CS_SIM_SAPATRREQUEST			TAPI_EVENT_SIM_SAP_TRANSFER_ATR_CNF
#define	TAPI_CS_SIM_SAPTRANSFERAPDU			TAPI_EVENT_SIM_SAP_TRANSFER_APDU_CNF
#define	TAPI_CS_SIM_SAPSETPROTOCOL			TAPI_EVENT_SIM_SAP_SET_PROTOCOL_CNF
#define	TAPI_CS_SIM_SAPSETSIMPOWER			TAPI_EVENT_SIM_SAP_SET_SIM_POWER_CNF
#define	TAPI_CS_SIM_SAPCARDREADERSTATUS		TAPI_EVENT_SIM_SAP_CARD_READER_STATUS_CNF
#define	TAPI_CS_SIM_AUTHENTICATION		TAPI_EVENT_SIM_AUTHENTICATION_CNF
#define TAPI_CS_SIM_APDU					TAPI_EVENT_SIM_APDU_CNF
#define TAPI_CS_SIM_ATR						TAPI_EVENT_SIM_ATR_CNF

// sync API
#define	TAPI_CS_SIM_GETIMSIINFO				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 1)
#define	TAPI_CS_SIM_GETFDNSTATUS			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 2)
#define	TAPI_CS_SIM_GETECCINFO				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 3)
#define	TAPI_CS_SIM_GETLANGUAGEINFO			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 4)
#define	TAPI_CS_SIM_GETCARDTYPE				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 5)
#define	TAPI_CS_SIM_GETSIMINITINFO			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 6)
#define	TAPI_CS_SIM_GETSECSTATUS			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 7)
#define	TAPI_CS_SIM_GETPBINITINFO			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 8)
#define	TAPI_CS_SIM_GETICCIDINFO			(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 9)
#define	TAPI_CS_SIM_GETCFINFO				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 10)
#define	TAPI_CS_SIM_GETMWINFO				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 11)
#define	TAPI_CS_SIM_GETMBINFO				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 12)
#define	TAPI_CS_SIM_GETCPHSINFO				(TAPI_CS_TYPE_SYNC+TAPI_EVENT_SIM_CNF_MAX + 13)

// SMS Service
#define	TAPI_CS_NETTEXT_EVENT_MAX			TAPI_EVENT_NETTEXT_GET_SMSBEARER_CNF
#define	TAPI_CS_NETTEXT_SEND				TAPI_EVENT_NETTEXT_SENTSTATUS_CNF
#define	TAPI_CS_NETTEXT_READ				TAPI_EVENT_NETTEXT_READ_SMS_CNF
#define	TAPI_CS_NETTEXT_WRITE				TAPI_EVENT_NETTEXT_SAVE_STATUS_CNF
#define	TAPI_CS_NETTEXT_DELETE				TAPI_EVENT_NETTEXT_DELETE_STATUS_CNF
#define	TAPI_CS_NETTEXT_GETCOUNT			TAPI_EVENT_NETTEXT_GET_COUNT_CNF
#define	TAPI_CS_NETTEXT_GETSCA				TAPI_EVENT_NETTEXT_GET_SCA_CNF
#define	TAPI_CS_NETTEXT_GETCBCONFIG			TAPI_EVENT_NETTEXT_GET_CB_CONFIG_CNF
#define	TAPI_CS_NETTEXT_GETPREFBEARER		TAPI_EVENT_NETTEXT_GET_SMSBEARER_CNF
#define	TAPI_CS_NETTEXT_SETDELIVERREPORT	TAPI_EVENT_NETTEXT_DELIVERY_REPORT_CNF
#define	TAPI_CS_NETTEXT_GETPARAMS			TAPI_EVENT_NETTEXT_GET_PARAM_CNF
#define	TAPI_CS_NETTEXT_GETPARAMCNT			TAPI_EVENT_NETTEXT_PARAM_COUNT_IND
#define	TAPI_CS_NETTEXT_SEND_EX				TAPI_EVENT_NETTEXT_SENTSTATUS_EX_CNF

// Same response
#define	TAPI_CS_NETTEXT_SETSCA				(TAPI_EVENT_NETTEXT_CNF_MAX + 1)
#define	TAPI_CS_NETTEXT_SETCBCONFIG			(TAPI_EVENT_NETTEXT_CNF_MAX + 2)
#define	TAPI_CS_NETTEXT_SETMEMSTATUS		(TAPI_EVENT_NETTEXT_CNF_MAX + 3)
#define	TAPI_CS_NETTEXT_SETPREFBEARER		(TAPI_EVENT_NETTEXT_CNF_MAX + 4)
#define	TAPI_CS_NETTEXT_SETMSGSTATUS		(TAPI_EVENT_NETTEXT_CNF_MAX + 5)
#define	TAPI_CS_NETTEXT_SETPARAMS			(TAPI_EVENT_NETTEXT_CNF_MAX + 6)

// Network Service
#define	TAPI_CS_NETWORK_EVENT_MAX			TAPI_EVENT_NETWORK_GET_CDMA_HYBRID_MODE_CNF
#define	TAPI_CS_NETWORK_SEARCH				TAPI_EVENT_NETWORK_SEARCH_CNF
#define	TAPI_CS_NETWORK_GETSELECTIONMODE	TAPI_EVENT_NETWORK_GETSELECTIONMODE_CNF
#define	TAPI_CS_NETWORK_SETNETWORKBAND		TAPI_EVENT_NETWORK_SETNWBAND_CNF
#define	TAPI_CS_NETWORK_GETNETWORKBAND		TAPI_EVENT_NETWORK_GETNWBAND_CNF
#define	TAPI_CS_NETWORK_SETNETWORKMODE		TAPI_EVENT_NETWORK_SETNWMODE_CNF
#define	TAPI_CS_NETWORK_GETNETWORKMODE		TAPI_EVENT_NETWORK_GETNWMODE_CNF
#define	TAPI_CS_NETWORK_SETPREFPLMN			TAPI_EVENT_NETWORK_SETPREFFEREDPLMN_CNF
#define	TAPI_CS_NETWORK_GETPREFPLMN			TAPI_EVENT_NETWORK_GETPREFFEREDPLMN_CNF
#define	TAPI_CS_NETWORK_SETSERVICEDOMAIN	TAPI_EVENT_NETWORK_SETSERVICEDOMAIN_CNF
#define	TAPI_CS_NETWORK_GETSERVICEDOMAIN	TAPI_EVENT_NETWORK_GETSERVICEDOMAIN_CNF
#define	TAPI_CS_NETWORK_SETROAMINGMODE		TAPI_EVENT_NETWORK_SET_ROAMING_MODE_CNF
#define	TAPI_CS_NETWORK_GETROAMINGMODE		TAPI_EVENT_NETWORK_GET_ROAMING_MODE_CNF
#define	TAPI_CS_NETWORK_SETCDMAHYBRIDMODE	TAPI_EVENT_NETWORK_SET_CDMA_HYBRID_MODE_CNF
#define	TAPI_CS_NETWORK_GETCDMAHYBRIDMODE	TAPI_EVENT_NETWORK_GET_CDMA_HYBRID_MODE_CNF
// Same response
#define	TAPI_CS_NETWORK_SELECT_AUTOMATIC	(TAPI_EVENT_NETWORK_CNF_MAX + 1)
#define	TAPI_CS_NETWORK_SELECT_MANUAL		(TAPI_EVENT_NETWORK_CNF_MAX + 2)

// SS Service
#define	TAPI_CS_SS_EVENT_MAX				TAPI_EVENT_SS_SET_AOC_CNF
#define	TAPI_CS_SS_BARRSETREQ				TAPI_EVENT_SS_BARRING_CNF
#define	TAPI_CS_SS_BARRCHANGEPWDREQ			TAPI_EVENT_SS_BARRING_CHANGEPASS_CNF
#define	TAPI_CS_SS_BARRQUERYSTATUSREQ		TAPI_EVENT_SS_BARRING_QUERYSTATUS_CNF
#define	TAPI_CS_SS_FWDSETREQ				TAPI_EVENT_SS_FORWARD_CNF
#define	TAPI_CS_SS_FWDQUERYSTATUSREQ		TAPI_EVENT_SS_FORWARD_QUERYSTATUS_CNF
#define	TAPI_CS_SS_WAITSETREQ				TAPI_EVENT_SS_WAITING_CNF
#define	TAPI_CS_SS_WAITQUERYSTATUSREQ		TAPI_EVENT_SS_WAITING_QUERYSTATUS_CNF
#define	TAPI_CS_SS_USSDSENDSTRINGREQ		TAPI_EVENT_SS_USSD_CNF
#define	TAPI_CS_SS_USSDCANCEL				TAPI_EVENT_SS_USSD_CANCEL_CNF
#define	TAPI_CS_SS_CLIQUERYSTATUSREQ		TAPI_EVENT_SS_CLI_QUERYSTATUS_CNF
#define	TAPI_CS_SS_GETCALLCOSTREQ			TAPI_EVENT_SS_AOC_RSP
#define	TAPI_CS_SS_SETCALLCOSTREQ			TAPI_EVENT_SS_SET_AOC_CNF
#define	TAPI_CS_SS_USSDRSP					TAPI_EVENT_SS_USSD_RSP_CNF
// SAT Service
#define	TAPI_CS_SIMATK_EVENT_MAX					TAPI_EVENT_SAT_MENU_SELECTION_CNF
#define	TAPI_CS_SIMATK_SEND_MENU_SELECTION_ENVELOPE	TAPI_EVENT_SAT_MENU_SELECTION_CNF
#define	TAPI_CS_SIMATK_SEND_EVENT_DOWNLOAD			TAPI_EVENT_SAT_EVENT_DOWNLOAD_CNF
#define	TAPI_CS_UI_DISPLAY_STATUS					(TAPI_EVENT_SAT_CNF_MAX + 1)
#define	TAPI_CS_UI_USER_CONFIRM						(TAPI_EVENT_SAT_CNF_MAX + 2)
#define	TAPI_CS_SIMATK_GET_MAIN_MENU_INFO			(TAPI_EVENT_SAT_CNF_MAX + 3)
#define	TAPI_CS_SIMATK_SEND_APP_EXEC_RESULT			(TAPI_EVENT_SAT_CNF_MAX + 4)

// GPRS Service
#define	TAPI_CS_GPRS_EVENT_MAX				TAPI_EVENT_PS_PDP_GET_PORTLIST_RSP
#define	TAPI_CS_GPRS_STARTNETWORK			TAPI_EVENT_PS_PDP_ACT_RSP
#define	TAPI_CS_GPRS_PDP_DEACTIVATION_SET	TAPI_EVENT_PS_PDP_DEACT_RSP
#define	TAPI_CS_GPRS_DATA_DORMANT			TAPI_EVENT_PS_DATA_DORMANT_RESP
#define	TAPI_CS_GPRS_PORT_LIST_SET			TAPI_EVENT_PS_PDP_SET_PORTLIST_RSP
#define	TAPI_CS_GPRS_PORT_LIST_GET			TAPI_EVENT_PS_PDP_GET_PORTLIST_RSP
#define	TAPI_CS_GPRS_BTDUN_PINCTRL_GET		(TAPI_EVENT_PS_CNF_MAX + 1)

// Sound Service
#define	TAPI_CS_SOUND_EVENT_MAX				TAPI_EVENT_SOUND_AUDIOSOURCECTRL_NOTI
#define	TAPI_CS_SOUND_VOLUME_GET			TAPI_EVENT_SOUND_VOLUMECTRL_RSP
#define	TAPI_CS_SOUND_MIC_MUTE_GET			TAPI_EVENT_SOUND_MICMUTECTRL_RSP
#define	TAPI_CS_SOUND_VOLUME_SET			(TAPI_EVENT_SOUND_CNF_MAX + 1)
#define	TAPI_CS_SOUND_MIC_MUTE_SET          (TAPI_EVENT_SOUND_CNF_MAX + 2)
#define	TAPI_CS_SOUND_AUDIO_PATH_CTRL		(TAPI_EVENT_SOUND_CNF_MAX + 3)

#define	TAPI_CS_UTIL_TUNNEL_REQ				(TAPI_EVENT_UTIL_TUNNEL_CNF)

// Internal
#define TAPI_CS_INTERNAL						(1<<30)

#define	TAPI_CS_SERVICE_DATA					TAPI_EVENT_CLASS_CDMA_DATA	//TAPI_EVENT_CLASS_CALL_DATA
#define	TAPI_CS_SERVICE_MISC					TAPI_EVENT_CLASS_MISC
#define	TAPI_CS_SERVICE_GPS						TAPI_EVENT_CLASS_GPS
#define	TAPI_CS_SERVICE_POWER					TAPI_EVENT_CLASS_POWER
#define	TAPI_CS_SERVICE_CFG						TAPI_EVENT_CLASS_CFG
#define	TAPI_CS_SERVICE_OMADM					TAPI_EVENT_CLASS_OMADM
#define	TAPI_CS_SERVICE_SVCMODE					TAPI_EVENT_CLASS_SVCMODE
#define	TAPI_CS_SERVICE_IMEI					TAPI_EVENT_CLASS_IMEI
#define	TAPI_CS_SERVICE_FACTORY					TAPI_EVENT_CLASS_FACTORY

// SMS Service
#define	TAPI_CS_NETTEXT_DEVICEREADY				(TAPI_CS_INTERNAL|(TAPI_EVENT_NETTEXT_CNF_MAX+ 1))
#define	TAPI_CS_NETTEXT_DEVICESTATUS			(TAPI_CS_INTERNAL|(TAPI_EVENT_NETTEXT_CNF_MAX+ 2))

// Network Service
#define	TAPI_CS_NETWORK_SETNETWORKORDER			(TAPI_CS_INTERNAL|(TAPI_CS_NETWORK_SELECT_MANUAL + 1))
#define	TAPI_CS_NETWORK_GETNETWORKORDER			(TAPI_CS_INTERNAL|(TAPI_CS_NETWORK_SELECT_MANUAL + 2))
#define	TAPI_CS_NETWORK_SETPOWERONATTACH		(TAPI_CS_INTERNAL|(TAPI_CS_NETWORK_SELECT_MANUAL + 3))
#define	TAPI_CS_NETWORK_GETPOWERONATTACH		(TAPI_CS_INTERNAL|(TAPI_CS_NETWORK_SELECT_MANUAL + 4))
#define	TAPI_CS_NETWORK_CANCELMANUALSEARCH		(TAPI_CS_INTERNAL|(TAPI_CS_NETWORK_SELECT_MANUAL + 5))
#define	TAPI_CS_NETWORK_CANCELMANUALSELECTION	(TAPI_CS_INTERNAL|(TAPI_CS_NETWORK_SELECT_MANUAL + 6))

// Sound Service
#define	TAPI_CS_SOUND_AUDIOLOOPBACK_SET			(TAPI_CS_INTERNAL|(TAPI_EVENT_SOUND_CNF_MAX + 1))
#define	TAPI_CS_SOUND_AUDIO_CLOCK_CTRL			(TAPI_CS_INTERNAL|(TAPI_EVENT_SOUND_CNF_MAX + 2))
#define	TAPI_CS_SOUND_VOICE_RECORDING_SET		(TAPI_CS_INTERNAL|(TAPI_EVENT_SOUND_CNF_MAX + 3))

// CDMA Data Service
#define	TAPI_CS_DATA_EVENT_MAX					(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_NAI_SETTING_MODE_SET_CNF))
#define	TAPI_CS_DATA_MOBILE_IP_NAI_SET			(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_MIP_NAI_SET_CNF))
#define	TAPI_CS_DATA_MOBILE_IP_NAI_GET			(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_MIP_NAI_GET_CNF))
#define	TAPI_CS_DATA_CURRENT_NAI_INDEX_GET		(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_CURRENT_NAI_INDEX_GET_CNF))
#define	TAPI_CS_DATA_TE2_STATUS_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_TE2_STATUS_GET_CNF))
#define	TAPI_CS_DATA_ROAM_GUARD_SET				(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_ROAM_GUARD_SET_CNF))
#define	TAPI_CS_DATA_ROAM_GUARD_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_ROAM_GUARD_GET_CNF))
#define	TAPI_CS_DATA_EVDO_REV_CONFIG_SET		(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_EVDO_REV_CONFIG_SET_CNF))
#define	TAPI_CS_DATA_EVDO_REV_CONFIG_GET		(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_EVDO_REV_CONFIG_GET_CNF))
#define	TAPI_CS_DATA_RESTORE_NAI				(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_RESTORE_NAI_SET_CNF))
#define	TAPI_CS_DATA_DDTM_CONFIGURATION_SET		(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_DDTM_CONFIGURATION_SET_CNF))
#define	TAPI_CS_DATA_DDTM_CONFIGURATION_GET		(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_DDTM_CONFIGURATION_GET_CNF))
#define	TAPI_CS_DATA_MODEM_NAI_SET				(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_NAI_SETTING_MODE_SET_CNF))
#define	TAPI_CS_DATA_MODEM_NAI_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_DATA_MODEM_NAI_GET_CNF)) // please check with TAPI_EVENT_DATA_NAI_SETTING_MODE_GET_CNF
// MISC Service
#define	TAPI_CS_MISC_EVENT_MAX					(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_NAM_INFO_NOTI))
#define	TAPI_CS_MISC_TIMEZONE_GETINFO			(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_NITZ_GETCNF))
#define	TAPI_CS_MISC_NAM_INFO_SET				(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_SET_NAM_INFO_CNF))
#define	TAPI_CS_MISC_NAM_INFO_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_GET_NAM_INFO_CNF))
#define	TAPI_CS_MISC_TIMEZONE_SETINFO			(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_CNF_MAX + 1))	// There is no confirm message
#define	TAPI_CS_MISC_TIMEZONE_CONFIRMINFO		(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_CNF_MAX + 2))	// It is not used and necessary. removed.
#define	TAPI_CS_MISC_TIMEZONE_GETMODE			(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_CNF_MAX + 3))
#define	TAPI_CS_MISC_SERIAL_NUMBER_GET			(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_CNF_MAX + 4))
#define	TAPI_CS_MISC_ME_VERSION_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_MISC_CNF_MAX + 5))

// GPS Service
#define	TAPI_CS_GPS_INIT						(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_INIT_RESP))
#define	TAPI_CS_GPS_DEINIT						(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_DEINIT_RESP))
#define	TAPI_CS_GPS_FIX_REQUEST					(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_FIX_REQUEST_RESP))
#define	TAPI_CS_GPS_STOP_SESSION				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_STOP_SESSION_RESP))
#define	TAPI_CS_GPS_GET_PARAMETERS				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_PARAMETERS_GET_RESP))
#define	TAPI_CS_GPS_SET_PARAMETERS				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_PARAMETERS_SET_RESP))
#define	TAPI_CS_GPS_AGPS_PDP_CONN_CNF			(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_PDP_CONNECTION_IND))
#define	TAPI_CS_GPS_AGPS_DNS_LOOKUP_CNF			(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_DNS_LOOKUP_IND))
#define	TAPI_CS_GPS_SEND_VER_CNF				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_VERIFICATION_IND))
#define	TAPI_CS_GPS_XTRA_INIT					(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_XTRA_INIT))
#define	TAPI_CS_GPS_XTRA_DEINIT					(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_XTRA_DEINIT))
#define	TAPI_CS_GPS_XTRA_ENABLE					(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_XTRA_ENABLE_SET_RESP))
#define	TAPI_CS_GPS_XTRA_DISABLE				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_CNF_MAX+1))	// should be fixed
#define	TAPI_CS_GPS_XTRA_SET_TIMEINFO			(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_XTRA_SET_TIME_RESP))
#define	TAPI_CS_GPS_XTRA_SET_DATA				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_XTRA_SET_DATA_RESP))
#define	TAPI_CS_GPS_MEASURE_POS_CNF				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_MEASURE_POSITION_CNF))
#define	TAPI_CS_GPS_SET_FREQ_AIDING				(TAPI_CS_INTERNAL|(TAPI_EVENT_GPS_FREQ_AIDING_SET_RESP))

// Power Service
#define	TAPI_CS_POWER_EVENT_MAX					(TAPI_CS_INTERNAL|(TAPI_EVENT_POWER_SERVICE_READY_IND))
#define	TAPI_CS_POWER_FLIGHT_MODE				(TAPI_CS_INTERNAL|(TAPI_EVENT_POWER_FLIGHT_MODE_RESP))
#define	TAPI_CS_POWER_PHONE_POWER_ON_OFF		(TAPI_CS_INTERNAL|(TAPI_CS_POWER_EVENT_MAX + 1))
#define	TAPI_CS_POWER_REBOOT					(TAPI_CS_INTERNAL|(TAPI_CS_POWER_EVENT_MAX + 2))
#define	TAPI_CS_POWER_RAMDUMP					(TAPI_CS_INTERNAL|(TAPI_CS_POWER_EVENT_MAX + 3))

// Power Service
#define	TAPI_CS_CFG_DEFAULTCONFGURATION_EXE		(TAPI_CS_INTERNAL|(TAPI_CFG_EVENT_DEFAULTCFG_IND))
#define	TAPI_CS_CFG_GET_A_KEY					(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_A_KEY_CNF))
#define	TAPI_CS_CFG_VERIFY_A_KEY				(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_VERIFY_A_KEY_CNF))
#define	TAPI_CS_CFG_GET_MSL_INFO				(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_MSL_INFO_CNF))
#define	TAPI_CS_CFG_SET_VOCODER_OPTION			(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_SET_VOCODER_OPTION_CNF))
#define	TAPI_CS_CFG_GET_VOCODER_OPTION			(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_VOCODER_OPTION_CNF))
#define	TAPI_CS_CFG_SET_HIDDEN_MENU_ACCESS		(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_SET_HIDDEN_MENU_ACCESS_CNF))
#define	TAPI_CS_CFG_GET_HIDDEN_MENU_ACCESS		(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_HIDDEN_MENU_ACCESS_CNF))
#define	TAPI_CS_CFG_SET_CURRENT_CARRIER			(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_SET_CURRENT_CARRIER_CNF))
#define	TAPI_CS_CFG_GET_CURRENT_CARRIER			(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_CURRENT_CARRIER_CNF))
#define	TAPI_CS_CFG_SET_SIO_MODE				(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_SET_SIO_MODE_CNF))
#define	TAPI_CS_CFG_GET_SIO_MODE				(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_SIO_MODE_CNF))
#define	TAPI_CS_CFG_GET_ACTIVATION_DATE			(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_ACTIVATION_DATE_CNF))
#define	TAPI_CS_CFG_GET_RECONDITIONED_DATE		(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_RECONDITIONED_DATE_CNF))
#define	TAPI_CS_CFG_SET_TTY_MODE				(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_SET_TTY_MODE_CNF))
#define	TAPI_CS_CFG_GET_TTY_MODE				(TAPI_CS_INTERNAL|(TAPI_EVENT_CFG_GET_TTY_MODE_CNF))

// Omadm Service
#define	TAPI_CS_OMADM_PRL_SIZE_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_OMADM_PRL_SIZE_GET_CNF))
#define	TAPI_CS_OMADM_MODEL_NAME_GET			(TAPI_CS_INTERNAL|(TAPI_EVENT_OMADM_MODEL_NAME_GET_CNF))
#define	TAPI_CS_OMADM_OEM_NAME_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_OMADM_OEM_NAME_GET_CNF))
#define	TAPI_CS_OMADM_SW_VER_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_OMADM_SW_VERSION_GET_CNF))
#define	TAPI_CS_OMADM_PRL_READ_GET				(TAPI_CS_INTERNAL|(TAPI_EVENT_OMADM_PRL_READ_GET_CNF))
#define	TAPI_CS_OMADM_PRL_WRITE_SET				(TAPI_CS_INTERNAL|(TAPI_EVENT_OMADM_PRL_WRITE_SET_CNF))

// Svc Service
#define	TAPI_CS_SVCMODE_EVENT_MAX				(TAPI_CS_INTERNAL|(TAPI_EVENT_SVCMODE_DEVICE_TEST_NOTI))
#define	TAPI_CS_SVCMODE_ENTERSVCMODE			(TAPI_CS_INTERNAL|(TAPI_EVENT_SVCMODE_START_NOTI))
#define	TAPI_CS_SVCMODE_ENDSVCMODE				(TAPI_CS_INTERNAL|(TAPI_EVENT_SVCMODE_END_NOTI))
#define	TAPI_CS_SVCMODE_PROCESS_KEYCODE			(TAPI_CS_INTERNAL|(TAPI_EVENT_SVCMODE_CNF_MAX + 1))
#define	TAPI_CS_SVCMODE_DEBUG_DUMP				(TAPI_CS_INTERNAL|(TAPI_EVENT_SVCMODE_DEBUG_DUMP_CNF))
#define	TAPI_CS_IMEI_COMPARE_ITEM_IND			(TAPI_CS_INTERNAL|(TAPI_EVENT_IMEI_COMPAREITEM))
#define	TAPI_CS_IMEI_STARTFACTORYPROCESS		(TAPI_CS_INTERNAL|(TAPI_EVENT_IMEI_CMLA_IND))

#define TAPI_CS_FACTORY_OMISSION_AVOIDANCE_SET	(TAPI_CS_INTERNAL|(TAPI_EVENT_FACTORY_OMISSION_AVOIDANCE_SET_CNF))
#define TAPI_CS_FACTORY_OMISSION_AVOIDANCE_GET	(TAPI_CS_INTERNAL|(TAPI_EVENT_FACTORY_OMISSION_AVOIDANCE_GET_CNF))

#ifdef __cplusplus
}
#endif

#endif /*_TEL_CS_CONN_H_ */
